### ISSUE TITLE
The Possibility of Server-Side Rendering or Pre-Rendering

### ISSUE THREAD

**Issue by JacobLinCool** [UniCourse-TW/Frontend#24]
**不在 MVP 計畫內！**

因為我們會有不同課程及文章的頁面，SSR 應該可以有效的增進 SEO 以及內容分享
之後可以考慮用 [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) 或 [Nuxt](https://v3.nuxtjs.org/) 來處理相關問題。

**Comment by Bogay** [comment]
@JacobLinCool 這能關了？[UniCourse-TW/realm](https://github.com/UniCourse-TW/realm) 算是完成目標了？
