### ISSUE TITLE
更新論壇排版

### ISSUE THREAD

**Issue by DWyatb** [UniCourse-TW/Frontend#43]

**Comment by DWyatb** [comment]
12/11 小記錄


1. 按鈕點選後位置亂跑
2. bbgroup /  b-icon套用失敗
https://bootstrap-vue.org/docs/components/button-group
https://bootstrap-vue.org/docs
https://bootstrap-vue.org/docs/icons
3. 尚未將文章搜尋結果及提問搜尋結果整合（需改到 postmeta type）
4. 確認公告文章格式是否與貼文相同

**Comment by skyhong2002** [comment]
想問 @DWyatb 你在哪個 branch 上，能先幫我開 PR 嗎？
