### ISSUE TITLE
課程、論壇等前後端連接

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/Frontend#55]
## 遇到的問題

- 課程無法正常搜尋
- 論壇提問及文章無法新增
- 甜度、涼度、實用度尚未隱藏

![image](https://user-images.githubusercontent.com/29522167/205240691-705e46d1-ab41-4195-9012-36a9f2bbd16e.png)

## 預期的行為

- 能夠正常搜尋課程
- 能正常新增及瀏覽論壇提問及文章
- 不會看到甜度、涼度、實用度（或是後端接上也可以，畢竟這個最後也是要做出來）
- 進入搜尋頁面能先顯示預設全域搜尋的結果

**Comment by uier** [comment]
> - 進入搜尋頁面能先顯示預設全域搜尋的結果

目前搜尋課程的參數 `q` 不能是空字串耶，要怎麼實現全域搜尋？

**Comment by uier** [comment]
update in branch `feat/api-call-for-course-n-post`

- [x] 能夠正常搜尋課程
- [ ] 能正常新增及瀏覽論壇提問及文章 https://github.com/UniCourse-TW/Backend/issues/55
- [x] 不會看到甜度、涼度、實用度（或是後端接上也可以，畢竟這個最後也是要做出來）
- [ ] 進入搜尋頁面能先顯示預設全域搜尋的結果

**Comment by skyhong2002** [comment]
> 目前搜尋課程的參數 q 不能是空字串耶，要怎麼實現全域搜尋？

或許可以 `q=order:name`，如果之後有依照熱門程度或亂序功能的話也可以替換

**Comment by uier** [comment]
> > 目前搜尋課程的參數 q 不能是空字串耶，要怎麼實現全域搜尋？
> 
> 或許可以 `q=order:name`，如果之後有依照熱門程度或亂序功能的話也可以替換

因為進階搜尋選單裡面有一個按某值排序的欄位，有預設值（假設叫它 `sortby`）
所以就先設定 `q=order:<sortby>`

**Comment by uier** [comment]
> update in branch `feat/api-call-for-course-n-post`
> 
> * [x]  能夠正常搜尋課程
> * [ ]  能正常新增及瀏覽論壇提問及文章 [Encounter 500 server error when create post Backend#55](https://github.com/UniCourse-TW/Backend/issues/55)
> * [x]  不會看到甜度、涼度、實用度（或是後端接上也可以，畢竟這個最後也是要做出來）
> * [x]  進入搜尋頁面能先顯示預設全域搜尋的結果

`能正常新增及瀏覽論壇提問及文章 https://github.com/UniCourse-TW/Backend/issues/55`
這一項另外開 issue，當 PR #63 獲准 merge 即關閉此 issue
