### ISSUE TITLE
[Critical] 首頁 LOGO 圖片預設字體

### ISSUE THREAD

**Issue by antingchao** [UniCourse-TW/Frontend#56]
窩們的眼睛要瞎ㄌ

![Image](https://user-images.githubusercontent.com/29522167/205317653-22e71e6d-1438-4fec-952b-3621b0267c63.png)

**Comment by antingchao** [comment]
@skyhong2002 我改在 front-page 的 branch 了，請你試一下字有沒有改，感謝～

**Comment by skyhong2002** [comment]
有～我想應該是成功了
https://unicourse-tw.github.io/Public-Assets/banner/banner_withText.svg

<img width="1224" alt="Screenshot 2022-12-04 at 18 11 37" src="https://user-images.githubusercontent.com/29522167/205485105-83471ab3-8e49-4109-b304-f3d6853081eb.png">

**Comment by skyhong2002** [comment]
能請 @antingchao 發 PR ㄇ

**Comment by antingchao** [comment]
好的！終於正常了哈哈哈
