### ISSUE TITLE
把圖片素材移至素材專用 Repo

### ISSUE THREAD

**Issue by JacobLinCool** [UniCourse-TW/Frontend#57]
素材應該都要移到 https://github.com/UniCourse-TW/Assets ，透過 CI 轉換到 https://github.com/UniCourse-TW/Public-Assets ，然後部署到 `https://unicourse-tw.github.io/Public-Assets/xxxxxxxxxxxxx`。

前端應使用 `https://unicourse-tw.github.io/Public-Assets/xxxxxxxxxxxxx` 作為圖片素材來源。

**Comment by antingchao** [comment]
目前用網址作為圖片來源、用 safari 開時，排版會跑掉，如圖（但用 chrome 可以正常顯示）


![Image](https://user-images.githubusercontent.com/98510877/205445284-f94d7257-6d4f-4c55-b93b-68f909d6597e.png)

**Comment by JacobLinCool** [comment]
> 首頁其他圖可能可以暫緩（嗎

我覺得可以，這部分應該不急，而且也看不出來

**Comment by skyhong2002** [comment]
This issue has not been updated for a while. Request @JacobLinCool / @antingchao to update.

**Comment by JacobLinCool** [comment]
我想應該 @antingchao 才有原圖，交給她處理可能比較好喔 0.0b

**Comment by JacobLinCool** [comment]
@antingchao 我要怎麼「用網址作為圖片來源」？https://github.com/UniCourse-TW/Assets 好像沒有檔案？
