### ISSUE TITLE
登入畫面新增記住帳號

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/Frontend#58]
# 遇到的問題

每次登入都還需要重新輸入一次帳號

# 預期的行為

在登入畫面新增記住帳號的按鈕，以便在之後登入時能更方便

**Comment by JacobLinCool** [comment]
你期望記住帳號的行為是什麼？長時間授權的 token 還是儲存密碼？

**Comment by skyhong2002** [comment]
> 你期望記住帳號的行為是什麼？長時間授權的 token 還是儲存密碼？

儲存帳號和/或密碼，長時間授權的 token 應該會開在另一個 issue，但無論 token 會是長時間還是短時間，使用者登入還需要重新輸入帳號和密碼。

不過這個功能其實在各大瀏覽器都有類似的，所以可能不算是太重要的功能。

**Comment by JacobLinCool** [comment]
那我覺得記住帳號就好了，記住密碼交給密碼管理器比較合適。
