### ISSUE TITLE
能正常新增及瀏覽論壇提問及文章

### ISSUE THREAD

**Issue by uier** [UniCourse-TW/Frontend#64]
- expected behavior: please refer to https://github.com/UniCourse-TW/Frontend/issues/55
- blocked by: https://github.com/UniCourse-TW/Backend/issues/55

**Comment by skyhong2002** [comment]
request @uier to update

**Comment by uier** [comment]
seems blocked by https://github.com/UniCourse-TW/Backend/issues/65

**Comment by JacobLinCool** [comment]
https://github.com/UniCourse-TW/Backend/issues/65 has been fixed in `v1.0.0-alpha.15`.

**Comment by skyhong2002** [comment]
This issue has expired since the project have been changed to https://github.com/UniCourse-TW/realm
