### ISSUE TITLE
登入歡迎訊息錯誤顯示為使用者 ID

### ISSUE THREAD

**Issue by JacobLinCool** [UniCourse-TW/Frontend#73]
<img width="477" alt="截圖 2023-01-08 上午4 11 33" src="https://user-images.githubusercontent.com/28478594/211168754-d19c1b95-0db6-4def-955c-a3e62b34c422.png">

**Comment by DWyatb** [comment]
修好 （在 each course new page 的 branch 中

![Image](https://user-images.githubusercontent.com/98510916/213841998-a527b4c6-dd83-4de7-b388-fb6ac057e4f4.png)

）
