### ISSUE TITLE
單一課程永久連結

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/Frontend#75]
相較於現況，期望每個課程都應該要有能夠分享課程的永久連結

![Image](https://user-images.githubusercontent.com/29522167/212548632-6e715389-8739-424b-ad16-49aef2fbe497.png)

每個課程的定義待確定，包含
- 最小等級的課程
- 同一個課程，但包含不同學期

**Comment by DWyatb** [comment]
已修好 [key].vue 的 type
